In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
treatments=pd.read_csv("treatments.csv")
adverse_reactions=pd.read_csv("/content/adverse_reactions.csv")
treatments_cut=pd.read_csv("treatments_cut.csv")
patients=pd.read_csv("patients.csv")

In [3]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [4]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [5]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [6]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [7]:
patients.info()
treatments.info()
treatments_cut.info()
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 948.0+ bytes

In [8]:
with pd.ExcelWriter("clinical_trails.xlsx") as writer:
  patients.to_excel(writer,sheet_name="patients")
  treatments.to_excel(writer,sheet_name="treatments")
  treatments_cut.to_excel(writer,sheet_name="treatments_cut")
  adverse_reactions.to_excel(writer,sheet_name="adverse_reaction")

##issues with data set       
1)Dirty data

Table-patients:

-> issue at patient_id 9 name misspelled as "dsvid" instead of david #accuracy ✅

->state cols some are given as shortforms some fullforms for eg"ny and newyork are both same" this may become issues in further #consistency ✅

-> pincode some are 5 digit and some are 4 digit inproper #validity ✅

->12 missing values in adress,city,state,zipcode,country,contact #completeness ✅

-> incorrect dtype assigned to assigned_sex,birthdate,zipcode #validity ✅

->duplicate entries by name of john doe #accuracy ✅

-> there is a girl of id 211 whose weight is 48 pound which is very less for her age ,height that's an entry issues #accuracy

-> id 4 height entry is wrong #accuracy

Table-treatments:
-> in this given_name,sur_name columns are all in lower case when whereas in patients table first letter is capital .it shows issues when we want to merge #consistency✅

->u can remove 'U' as value is u for all #VALIDITY ✅

-> hiphen - in novolon and auralin should be replaced by Nan as comp does not consider as isempty if - is there it considers it as another value #VALIDITY ✅

->some missing values in hba1c_change #completeness ✅

->1 duplicate entry by name joseph day #accuracy✅

->in hba1c_change 9 is mistken instead of 4 for most of cases #accuracy ✅

Table- treatments_cut:

-> in this given_name,sur_name columns are all in lower case when whereas in patients table first letter is capital .it shows issues when we want to merge #consistency✅

->u can remove u as value is u for all #VALIDITY ✅

-> hiphen - in novolon and auralin should be replaced by Nan as comp does not consider as isempty if - is there it considers it as another value #validity ✅

->some missing values in hba1c_change #completeness ✅

->1 duplicate entry by name joseph day #accuracy ✅

->in hba1c_change 9 is mistken instead of 4 for most of cases #accuracy ✅

Table- adverse_reactions:

-> in this given_name,sur_name columns are all in lower case when whereas in patients table first letter is capital .it shows issues when we want to merge #consistency ✅





2) Messy data ✅

Table-patients:

->patient number and email are merged into single cell so seperate✅

Table-treatments:

-> auralin novodra should be split into two as start and end values ->merge treatments &treatments_cut✅

Table-treatments_cut:

-> auralin novodra should be split into two as start and end values✅

Table- adverse_reactions:

-> adverse table should not exist manually,is unnecessary actually u can add it beside treatments✅

# Automatic assements
1)head and tail
2)info
3)sample
4)isnull
5)duplicated
6)describe

In [9]:
patients[patients["address"].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

#automatic issue
patients table:
  ->assigned_sex is given dtype object it should be converted to categorical
  ->zip_code is float occpy unnecessary data so should be converted into int
  -> birthdate should be converted from object to date

In [10]:
treatments[treatments["hba1c_change"].isnull()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
269,hiromu,horikawa,-,47u - 46u,7.77,7.28,NaN
271,leo,vieira,-,30u - 33u,7.74,7.36,NaN
273,kate,wilkinson,36u - 39u,-,7.72,7.20,NaN
274,naja,enoksen,43u - 50u,-,7.98,7.59,NaN
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN

In [11]:
treatments_cut[treatments_cut["hba1c_change"].isnull()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
6,sara,miles,30u - 35u,-,7.53,7.12,NaN
7,frydryk,adamski,63u - 74u,-,7.75,7.27,NaN
8,jane,citizen,-,37u - 38u,7.98,7.60,NaN
11,gabriela,michalčíková,26u - 36u,-,8.37,7.97,NaN
14,chiho,higa,-,46u - 46u,7.71,7.30,NaN
17,emma,barlow,48u - 57u,-,7.85,7.39,NaN
21,david,villadsen,26u - 39u,-,7.86,7.40,NaN
24,lóa,hrafnsdóttir,22u - 31u,-,7.60,7.09,NaN
28,una,traustadóttir,-,35u - 34u,8.00,7.50,NaN
30,trifon,izmailov,58u - 63u,-,7.68,7.28,NaN
38,guðni,heimisson,-,40u - 36u,7.64,7.24,NaN
39,maryam,dratchev,37u - 45u,-,9.91,9.46,NaN
43,hans peter,radislav,42u - 53u,-,7.60,7.20,NaN
44,jeremy,montagu,-,52u - 52u,7.68,7.36,NaN
45,štefanija,novosel,37u - 42u,-,7.64,7.17,NaN
47,regolo,nucci,51u - 59u,-,7.53,7.02,NaN
51,bjørnar,nilsen,-,36u - 33u,7.99,7.70,NaN
52,vivien,zsinkó,30u - 38u,-,8.35,7.92,NaN
54,borna,šlezinger,-,42u - 41u,7.55,7.18,NaN
55,mary,adams,-,32u - 33u,7.65,7.26,NaN
56,blanka,jurković,31u - 43u,-,7.77,7.33,NaN
60,maret,sultygov,-,26u - 23u,7.67,7.30,NaN
62,fakhri,fakhoury,39u - 50u,-,7.83,7.39,NaN
63,žarka,rap,35u - 48u,-,7.54,7.15,NaN
68,berta,napolitani,-,42u - 44u,7.68,7.21,NaN
69,armina,sauvé,36u - 46u,-,7.86,7.40,NaN

In [12]:
patients.duplicated().sum()

np.int64(0)

In [13]:
treatments.duplicated().sum()

np.int64(1)

In [14]:
treatments_cut.duplicated().sum()

np.int64(0)

In [15]:
adverse_reactions.duplicated().sum()

np.int64(0)

In [16]:
#in each table check each coloum for duplicate or not
patients["patient_id"].duplicated().sum()
#no duplicate ids

np.int64(0)

In [17]:
#check in combo of name and surname
patients[patients.duplicated(subset=['given_name',"surname"])]
#multiple entries by single person

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [18]:
treatments[treatments.duplicated(subset=["given_name","surname"])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [19]:
treatments_cut[treatments_cut.duplicated(subset=["given_name","surname"])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [20]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [21]:
patients[patients['weight']==48.80000]
#how can a patient be of age more and height 63 inches which is 5.5 feet and weight 48 pound ==21 kg
#blackhole

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [22]:
patients[patients['height']==27.000000]
#how can a patient be of age more and height 27 inches which is 2.5 feet and weight 192 pound ==80 kg
#blackhole

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [23]:
treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [24]:
treatments.sort_values('hba1c_change')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
70,tosh,jensen,-,51u - 48u,7.93,7.69,0.24
237,manouck,wubbels,55u - 62u,-,7.66,7.40,0.26
200,nicolas,ferreira,43u - 51u,-,7.99,7.72,0.27
156,chidalu,onyekaozulu,-,42u - 41u,7.54,7.27,0.27
...,...,...,...,...,...,...,...
269,hiromu,horikawa,-,47u - 46u,7.77,7.28,NaN
271,leo,vieira,-,30u - 33u,7.74,7.36,NaN
273,kate,wilkinson,36u - 39u,-,7.72,7.20,NaN
274,naja,enoksen,43u - 50u,-,7.98,7.59,NaN
276,john,teichelmann,-,49u - 49u,7.90,7.58,NaN

In [25]:
treatments_cut.describe()

       hba1c_start  hba1c_end  hba1c_change
count    70.000000  70.000000     42.000000
mean      7.838000   7.443143      0.518810
std       0.423007   0.418706      0.270719
min       7.510000   7.020000      0.280000
25%       7.640000   7.232500      0.340000
50%       7.730000   7.345000      0.370000
75%       7.860000   7.467500      0.907500
max       9.910000   9.460000      0.970000

Data quality dimesnions


*  completeness -> is data missing?
*  validty-> is data invalid -> negative height -> duplicate patient id
*  accuracy -> data is valid but not accurate ->weight -> 1kg
*  consistency -> both valid and accurate but written differently ->new york and ny

order of severity
completeness <- validity <- accuracy <- consistency

**Data cleaning order**
1. quality-> completeness
2.   tidiness(messy)
3.  quality->vaildity
4.  quality->accuracy
5.  quality->consistency


**steps involves in cleaning **
* define
* order
* test

always make a copy of data before cleaning

In [26]:
patients_df=patients.copy()
treatments_df=treatments.copy()
treatments_cut_df=treatments_cut.copy()
adverse_df=adverse_reactions.copy()

### define
**completeness
-replace all missing values in patients df with no data
-substarct hba1c _start -hba1c_end to get all hba1c_change values
**messey data
-in patient data we use regular expression to seperate email and phoneno
-merge treatments &treatments_cut
-seperate novodra and auralin start and end values change there dtype
-merge adverse with treatments

In [27]:
#first work on completeness issues
#code
patients_df.fillna("no data ",inplace =True)
#test
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   contact       503 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 55.1+ KB

<ipython-input-27-ac3f4ae97cdd>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'no data ' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  patients_df.fillna("no data ",inplace =True)

In [28]:
treatments_df['hba1c_change']=treatments_df['hba1c_start']-treatments_df['hba1c_end']
treatments_df.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [29]:
treatments_cut_df['hba1c_change']=treatments_cut_df['hba1c_start']-treatments_cut_df['hba1c_end']
treatments_cut_df.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,0.40
2,alwin,svensson,36u - 39u,-,7.78,7.34,0.44
3,thể,lương,-,61u - 64u,7.64,7.22,0.42
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [30]:
tt=pd.concat([treatments_df,treatments_cut_df])
tt.info()
tt.head()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    object
 1   surname       350 non-null    object
 2   auralin       350 non-null    object
 3   novodra       350 non-null    object
 4   hba1c_start   350 non-null    float64
 5   hba1c_end     350 non-null    float64
 6   hba1c_change  350 non-null    float64
dtypes: float64(3), object(4)
memory usage: 21.9+ KB

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [31]:
#instead of two seperate drug auralin and novodra we are combing them as 1
tt_df=tt.melt(id_vars=['given_name','surname','hba1c_start','hba1c_end','hba1c_change'],var_name='typeofdrug',value_name='dosage')
tt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    700 non-null    object
 1   surname       700 non-null    object
 2   hba1c_start   700 non-null    float64
 3   hba1c_end     700 non-null    float64
 4   hba1c_change  700 non-null    float64
 5   typeofdrug    700 non-null    object
 6   dosage        700 non-null    object
dtypes: float64(3), object(4)
memory usage: 38.4+ KB

In [32]:
tt_df.head()
#here its giving all null dosage values making entries 700

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,typeofdrug,dosage
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
1,elliot,richardson,7.56,7.09,0.47,auralin,-
2,yukitaka,takenaka,7.68,7.25,0.43,auralin,-
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
4,alissa,montez,7.78,7.46,0.32,auralin,-

In [33]:
 #here we reduce the null entries and making form lesser
 tt_df1=tt_df[tt_df['dosage']!='-']
 tt_df1.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,typeofdrug,dosage
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u

In [34]:
tt_df1.info()
#here we got again 350 entries only

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    object
 1   surname       350 non-null    object
 2   hba1c_start   350 non-null    float64
 3   hba1c_end     350 non-null    float64
 4   hba1c_change  350 non-null    float64
 5   typeofdrug    350 non-null    object
 6   dosage        350 non-null    object
dtypes: float64(3), object(4)
memory usage: 21.9+ KB

In [35]:
#splliting start and end value
tt_df1['dosage_start']=tt_df1["dosage"].str.split("-").str.get(0)
tt_df1['dosage_end']=tt_df1["dosage"].str.split("-").str.get(1)

<ipython-input-35-0374c52d7985>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt_df1['dosage_start']=tt_df1["dosage"].str.split("-").str.get(0)
<ipython-input-35-0374c52d7985>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt_df1['dosage_end']=tt_df1["dosage"].str.split("-").str.get(1)

In [36]:
tt_df1.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,typeofdrug,dosage,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u,31u,38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u,30u,36u

In [37]:
#since we seperated start and end values we can drop sosage single col
tt_df1.drop(columns='dosage',inplace=True)

<ipython-input-37-f3198f9dcd01>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt_df1.drop(columns='dosage',inplace=True)

In [38]:
#removing 'U' from dosage values
tt_df1['dosage_start']=tt_df1["dosage_start"].str.replace("u",'')
tt_df1['dosage_end']=tt_df1["dosage_end"].str.replace("u",'')

<ipython-input-38-6ce0baa7ada4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt_df1['dosage_start']=tt_df1["dosage_start"].str.replace("u",'')
<ipython-input-38-6ce0baa7ada4>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt_df1['dosage_end']=tt_df1["dosage_end"].str.replace("u",'')

In [39]:
tt_df1.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,typeofdrug,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
3,skye,gormanston,7.97,7.62,0.35,auralin,33,36
6,sophia,haugen,7.65,7.27,0.38,auralin,37,42
7,eddie,archer,7.89,7.55,0.34,auralin,31,38
9,asia,woźniak,7.76,7.37,0.39,auralin,30,36

In [40]:
#changing datatype
tt_df1['dosage_start']=tt_df1["dosage_start"].astype("int")
tt_df1['dosage_end']=tt_df1["dosage_end"].astype("int")

<ipython-input-40-35e43bccfc74>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt_df1['dosage_start']=tt_df1["dosage_start"].astype("int")
<ipython-input-40-35e43bccfc74>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tt_df1['dosage_end']=tt_df1["dosage_end"].astype("int")

In [41]:
tt_df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    object
 1   surname       350 non-null    object
 2   hba1c_start   350 non-null    float64
 3   hba1c_end     350 non-null    float64
 4   hba1c_change  350 non-null    float64
 5   typeofdrug    350 non-null    object
 6   dosage_start  350 non-null    int64
 7   dosage_end    350 non-null    int64
dtypes: float64(3), int64(2), object(3)
memory usage: 24.6+ KB

In [42]:
#removing adverse_reactions tabe by merging with treatments
finaltt=tt_df1.merge(adverse_df,how="left" ,on=['given_name',"surname"])
finaltt.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,typeofdrug,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN

In [43]:
finaltt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        350 non-null    object
 1   surname           350 non-null    object
 2   hba1c_start       350 non-null    float64
 3   hba1c_end         350 non-null    float64
 4   hba1c_change      350 non-null    float64
 5   typeofdrug        350 non-null    object
 6   dosage_start      350 non-null    int64
 7   dosage_end        350 non-null    int64
 8   adverse_reaction  35 non-null     object
dtypes: float64(3), int64(2), object(4)
memory usage: 24.7+ KB

In [44]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   contact       503 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 55.1+ KB

In [45]:
# Convert assigned_sex to categorical
patients_df['assigned_sex'] = patients_df['assigned_sex'].astype('category')
# For birthdate - convert to datetime
patients_df['birthdate'] = pd.to_datetime(patients_df['birthdate'])
#for zip_code convert to int is not possible as we are converting some inpropoer 4 didgit codes into all 5 digits but leading zeros will disappear, e.g., 07095 → 7095)

In [46]:
import pandas as pd

# Step 1: Convert to string and strip whitespace
patients_df['zip_code'] = patients_df['zip_code'].astype(str).str.strip()

# Step 2: Remove '.0' from floats (e.g., "7095.0" → "7095")
patients_df['zip_code'] = patients_df['zip_code'].str.replace(r'\.0$', '', regex=True)

# Step 3: Fill missing/empty values with '00000' (or use `pd.NA` if preferred)
patients_df['zip_code'] = patients_df['zip_code'].replace('nan', '00000')  # Handles NaN
patients_df['zip_code'] = patients_df['zip_code'].replace('', '00000')     # Handles empty strings

# Step 4: Pad with leading zeros to ensure 5 digits
patients_df['zip_code'] = patients_df['zip_code'].str.zfill(5)

# Verify
print(patients_df['zip_code'].sample(10))  # Check random samples
print(patients_df['zip_code'].str.len().value_counts())  # All should be 5 now

163    29180
247    10011
173    48057
484    28716
134    12207
394    75757
125    74119
130    29420
267    67401
241    38002
Name: zip_code, dtype: object
zip_code
5    491
7     12
Name: count, dtype: int64

In [47]:
patients_df.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390,United States,951-719-9170ZoeWellish@superrito.com,1976-07-10,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,1967-04-03,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467,United States,402-363-6804JaeMDebord@gustr.com,1980-02-19,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,07095,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,1951-07-26,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303,United States,334-515-7487TimNeudorf@cuvox.de,1928-02-18,192.3,27,26.1

In [48]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    category
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   contact       503 non-null    object
 10  birthdate     503 non-null    datetime64[ns]
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: category(1), datetime64[ns](1), float64(2), int64(2), object(8)
memory usage: 51.8+ KB

In [49]:
patients_df.loc[patients_df['patient_id'] == 9, 'given_name'] = "David"
print(patients_df[patients_df['patient_id'] == 9][['patient_id', 'given_name']])

   patient_id given_name
8           9      David

In [50]:
!pip install us

Requirement already satisfied: us in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: jellyfish in /usr/local/lib/python3.11/dist-packages (from us) (1.2.0)

In [51]:
#state cols some are given as shortforms some fullforms for eg"ny and newyork are both same" so converting
import pandas as pd
from us import states

# Create mapping dictionary
state_mapping = {state.name: state.abbr for state in states.STATES}
state_mapping.update({state.abbr: state.abbr for state in states.STATES})

# Apply standardization
patients_df['state'] = patients_df['state'].map(state_mapping)

In [52]:
import re
def split_contact(contact):
    if pd.isna(contact) or contact == '':
        return pd.Series([None, None])

    # Improved regex pattern to find emails
    email_pattern = r'([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})'
    email_match = re.search(email_pattern, contact)

    # Improved regex pattern to find phone numbers
    phone_pattern = r'(\+?\d[\d\s\(\)\-\.]{7,}\d)'
    phone_match = re.search(phone_pattern, contact)

    email = email_match.group(0) if email_match else None
    phone = phone_match.group(0) if phone_match else None

    # Clean phone number
    if phone:
        # Remove all non-digit characters except leading +
        phone = re.sub(r'(?!^\+)\D', '', phone)
        # Format US numbers nicely
        if len(phone) == 10:
            phone = f"({phone[:3]}) {phone[3:6]}-{phone[6:]}"
        elif len(phone) == 11 and phone.startswith('1'):
            phone = f"+1 ({phone[1:4]}) {phone[4:7]}-{phone[7:]}"

    return pd.Series([phone, email])

# Apply the improved function
patients_df[['phone', 'email']] = patients_df['contact'].apply(split_contact)
patients_df =patients_df.drop(columns=['contact'])

In [53]:
patients_df.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,CA,92390,United States,1976-07-10,121.7,66,19.6,(951) 719-9170,951-719-9170ZoeWellish@superrito.com
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,IL,61812,United States,1967-04-03,118.8,66,19.2,+12175693204,PamelaSHill@cuvox.de
2,3,male,Jae,Debord,1493 Poling Farm Road,York,NE,68467,United States,1980-02-19,177.8,71,24.8,(402) 363-6804,402-363-6804JaeMDebord@gustr.com
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,07095,United States,1951-07-26,220.9,70,31.7,+17326368246,PhanBaLiem@jourrapide.com
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303,United States,1928-02-18,192.3,27,26.1,(334) 515-7487,334-515-7487TimNeudorf@cuvox.de

In [60]:
patients_df['full_name'] = patients_df['given_name'] + ' ' + patients_df['surname']
patients_df= patients_df.drop_duplicates(subset=['full_name'], keep='first')
patients_df =patients_df.drop(columns=['full_name'])  # Remove the temporary column

In [61]:
patients_df['phone'] = patients_df['phone'].fillna("no data ")
patients_df['email'] = patients_df['email'].fillna("no data ")
patients_df['zip_code'] = patients_df['zip_code'].fillna("no data ")
finaltt['adverse_reaction'] = finaltt['adverse_reaction'].fillna("no data ")

In [62]:
# in this given_name,sur_name columns are all in lower case when whereas in patients table first letter is capital .it shows issues when we want to merge so capitalizing all startig Alphabet
def capitalize_names(name_series):
    return (
        name_series
        .astype(str)  # Ensure it's string type
        .str.strip()  # Remove whitespace
        .str.lower()  # First convert to lowercase
        .str.title()  # Then capitalize first letters
        .str.replace(r"\b(Mc|Mac|O')[a-z]", lambda x: x.group(0)[:-1] + x.group(0)[-1].upper(), regex=True)  # Handle special cases
    )
finaltt['given_name'] = capitalize_names(finaltt['given_name'])
finaltt['surname'] = capitalize_names(finaltt['surname'])

In [63]:
finaltt.info()
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        350 non-null    object
 1   surname           350 non-null    object
 2   hba1c_start       350 non-null    float64
 3   hba1c_end         350 non-null    float64
 4   hba1c_change      350 non-null    float64
 5   typeofdrug        350 non-null    object
 6   dosage_start      350 non-null    int64
 7   dosage_end        350 non-null    int64
 8   adverse_reaction  350 non-null    object
dtypes: float64(3), int64(2), object(4)
memory usage: 24.7+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 498 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    498 non-null    int64
 1   assigned_sex  498 non-null    category
 2   given_name    498 non-null    object
 3   surname       498 non-null    object
 4   address       498 non-null    object
 5   city          498 non-null    object
 6   state         484 non-null    object
 7   zip_code      498 non-null    object
 8   country       498 non-null    object
 9   birthdate     498 non-null    datetime64[ns]
 10  weight        498 non-null    float64
 11  height        498 non-null    int64
 12  bmi           498 non-null    float64
 13  phone         498 non-null    object
 14  email         498 non-null    object
dtypes: category(1), datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 59.0+ KB

In [64]:
with pd.ExcelWriter("perfectclinical_trails.xlsx") as writer:
  patients_df.to_excel(writer,sheet_name="modified_patients")
  finaltt.to_excel(writer,sheet_name="merged treatments,treatments_cut,adverse_reactions")

/usr/local/lib/python3.11/dist-packages/openpyxl/workbook/child.py:99: UserWarning: Title is more than 31 characters. Some applications may not be able to read the file
  warnings.warn("Title is more than 31 characters. Some applications may not be able to read the file")